"""New InventoryItem table and changes in Characte table

Revision ID: 057c61a5c98e
Revises: 642e2f001023
Create Date: 2026-09-30 11:13:21.911771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057c61a5c98e'
down_revision: Union[str, Sequence[str], None] = '642e2f001023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'item_id', name='uq_character_item')
    )
    op.create_index(op.f('ix_inventory_items_character_id'), 'inventory_items', ['character_id'], unique=False)
    op.add_column('characters', sa.Column('helmet_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('chestplate_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('legging_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('boot_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('main_hand_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('off_hand_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('usage_id', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('shell_id', sa.String(length=50), nullable=True))
    op.drop_column('characters', 'inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('inventory', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('characters', 'shell_id')
    op.drop_column('characters', 'usage_id')
    op.drop_column('characters', 'off_hand_id')
    op.drop_column('characters', 'main_hand_id')
    op.drop_column('characters', 'boot_id')
    op.drop_column('characters', 'legging_id')
    op.drop_column('characters', 'chestplate_id')
    op.drop_column('characters', 'helmet_id')
    op.drop_index(op.f('ix_inventory_items_character_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
