"""Added Unique for Character.owner_id

Revision ID: 89b166348058
Revises: c31b22919a83
Create Date: 2026-10-01 15:13:24.408517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b166348058'
down_revision: Union[str, Sequence[str], None] = 'c31b22919a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    # ### end Alembic commands ###
