"""UniqueConstraint removed from InventoryItem

Revision ID: c31b22919a83
Revises: 057c61a5c98e
Create Date: 2026-10-01 10:07:49.020304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31b22919a83'
down_revision: Union[str, Sequence[str], None] = '057c61a5c98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_character_item'), 'inventory_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_character_item'), 'inventory_items', ['character_id', 'item_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
